services:
  backend:
    image: akhilbm/todo-backend:2.0
    container_name: todo-backend
    env_file:
      - .env

  frontend:
    image: akhilbm/todo-frontend:2.0
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
