services:
  backend:
    image: akhilbm/todo-backend:1.1
    container_name: todo-backend
    env_file:
      - .env
    volumes:
      - todo-data:/app/instance/data

  frontend:
    image: akhilbm/todo-frontend:1.1
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  todo-data:
